# uvconfigmacros.cmake

macro(uv_initialize_build_flags)
    set(CMAKE_CXX_STANDARD 17)

    set(CMAKE_CXX_STANDARD 17)

    set(CMAKE_AUTOMOC ON)
    set(CMAKE_AUTORCC ON)
    set(CMAKE_AUTOUIC ON)

    #set(CMAKE_BUILD_TYPE RelWithDebInfo)
    set(CMAKE_INSTALL_PREFIX ${CMAKE_BINARY_DIR}/install/)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/)
endmacro()